### ISSUE TITLE
Polymorph button does not appear when multiple items share a recipe

### ISSUE THREAD

**Issue by brandonlee781** [Erdragh/ProjectTable#19]
https://www.curseforge.com/minecraft/mc-mods/polymorph

In the vanilla Crafting table a button will appear above the grid if multiple items share a recipe. This button does not appear on the Project Table

**Comment by Erdragh** [comment]
I'll take a look and try to implement this as soon as possible.

Just putting this here for my own reference: https://github.com/illusivesoulworks/polymorph/blob/1.20.x/common/src/main/java/com/illusivesoulworks/polymorph/mixin/core/MixinCraftingMenu.java

**Comment by Erdragh** [comment]
![2023-11-12_21 40 12](https://github.com/Erdragh/ProjectTableRefabricated/assets/29674493/25974e5b-9947-44fb-9b3f-7cecf7392f0f)
Almost done, only need to make it not crash without polymorph installed.

**Comment by Erdragh** [comment]
The next update will come out soon and include this fix
